baseurl = "/"
languageCode = "vi-VN"
title = "Trong-Thang Pham's Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    note = "/note/:year/:month/:day/:slug/"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/phamtrongthang123"
    weight = 5
[[menu.main]]
    name = "Google Scholars"
    url = "https://scholar.google.com/citations?user=SwR0T0UAAAAJ&hl=en"
    weight = 6
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/phamtrongthanghcmus/"
    weight = 7

[[menu.main]]
    name = "CV"
    url = "https://drive.google.com/file/d/1aXYRX2aj9pHeakYM7PkOkOVQQl8XwOxr/view?usp=sharing"
    weight = 8
[params]
    description = "Trong-Thang Pham's blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true