---
title: 'Hệ điều hành: Bài toán xếp lịch'
author: Trong-Thang Pham
date: '2019-12-12'
slug: hệ-điều-hành-bài-toán-xếp-lịch
categories:
  - Study at university
tags:
  - Note
  - Operating System
  - Hệ điều hành 
  
output:
  blogdown::html_page:
    toc: true
---
### 6.1 
A CPU-scheduling algorithm determines an order for the execution
of its scheduled processes. Given n processes to be scheduled on one
processor, how many different schedules are possible? Give a formula
in terms of n.

#### Answer:

### 6.2 
Explain the difference between preemptive and nonpreemptive scheduling.

#### Answer:

### 6.3 
Suppose that the following processes arrive for execution at the times
indicated. Each process will run for the amount of time listed. In
answering the questions, use nonpreemptive scheduling, and base all
decisions on the information you have at the time the decision must be
made.

Process | Arrival Time | Burst Time
---|---|---
P1 |0.0 | 8
P2 | 0.4 | 4
P3 | 1.0 | 1

a. What is the average turnaround time for these processes with the
FCFS scheduling algorithm?

b. What is the average turnaround time for these processes with the
SJF scheduling algorithm?

c. The SJF algorithm is supposed to improve performance, but notice
that we chose to run process P1 at time 0 because we did not know
that two shorter processes would arrive soon. Compute what the
average turnaround time will be if the CPU is left idle for the first
1 unit and then SJF scheduling is used. Remember that processes
P1 and P2 are waiting during this idle time, so their waiting time
may increase. This algorithm could be called future-knowledge
scheduling.

#### Answer:


### 6.4 
What advantage is there in having different time-quantum sizes at
different levels of a multilevel queueing system?

#### Answer:


### 6.5 
Many CPU-scheduling algorithms are parameterized. For example, the
RR algorithm requires a parameter to indicate the time slice. Multilevel
feedback queues require parameters to define the number of queues, the
scheduling algorithm for each queue, the criteria used to move processes
between queues, and so on.

These algorithms are thus really sets of algorithms (for example, the
set of RR algorithms for all time slices, and so on). One set of algorithms
may include another (for example, the FCFS algorithm is the RR algorithm
with an infinite time quantum). What (if any) relation holds between the
following pairs of algorithm sets?

a. Priority and SJF

b. Multilevel feedback queues and FCFS

c. Priority and FCFS

d. RR and SJF

#### Answer:

### 6.6 
Suppose that a scheduling algorithm (at the level of short-term CPU
scheduling) favors those processes that have used the least processor
time in the recent past. Why will this algorithm favor I/O-bound
programs and yet not permanently starve CPU-bound programs?

#### Answer:


### 6.7 
Distinguish between PCS and SCS scheduling.

#### Answer:


### 6.8 
Assume that an operating system maps user-level threads to the kernel
using the many-to-many model and that the mapping is done through
the use of LWPs. Furthermore, the system allows program developers to
create real-time threads. Is it necessary to bind a real-time thread to an
LWP?

#### Answer:


### 6.9 
The traditional UNIX scheduler enforces an inverse relationship between
priority numbers and priorities: the higher the number, the lower the
priority. The scheduler recalculates process priorities once per second
using the following function:

`Priority = (recent CPU usage / 2) + base`

where `base = 60` and `recent CPU usage` refers to a value indicating how
often a process has used the CPU since priorities were last recalculated.
Assume that recent CPU usage is 40 for process P1, 18 for process P2,
and 10 for process P3. What will be the new priorities for these three
processes when priorities are recalculated? Based on this information,
does the traditional UNIX scheduler raise or lower the relative priority
of a CPU-bound process?

#### Answer:
