---
title: 'Hệ điều hành: bộ nhớ'
author: Trong-Thang Pham
date: '2019-12-12'
slug: hệ-điều-hành-bộ-nhớ
categories:
  - Study at university
tags:
  - Hệ điều hành
  - Note
  - Operating System

output:
  blogdown::html_page:
    toc: true
---
Bắt đầu ôn bài thôi nhỉ. Từ đây sẽ là chuỗi bài ôn bài HDH cuối kì cho mình. 
Mình sẽ đi theo hướng giải bt vì nếu tóm tắt sẽ không đủ thời gian để hoàn thành. :( 
 
### 8.1 
Name two differences between logical and physical addresses

#### Answer:

>
* user sẽ thấy theo logical  - còn thực tế sử dụng physical 
* logial từ 0 -> max - physical được map qua R+0 -> R+max 
* logical được CPU sinh ra - physical thì memory unit đọc được 

### 8.2 
Consider a system in which a program can be separated into two parts: code and data. The CPU knows whether it wants an instruction (instruction fetch) or data (data fetch or store). Therefore, two base-limit register pairs are provided: one for instructions and one for data. The instruction base–limit register pair is automatically read-only, so programs can be shared among different users. Discuss the advantages and disadvantages of this scheme.

#### Answer:
>


### 8.3 
Why are page sizes always powers of 2?

#### Answer:

> t chỉ tìm ra lý do nằm ở việc tính dễ hơn thôi, không biết sách có đề cập gì thêm không.

### 8.4 
Consider a logical address space of 64 pages of 1,024 words each, mapped onto a physical memory of 32 frames.

  a. How many bits are there in the logical address?

> ủa word là ít nhất 1 byte, còn này không nói rõ gì cả :'( Vậy xem word là 1 byte nhé 
> 
> 2^10 * 2^3 * 2^6

  b. How many bits are there in the physical address?

> 2^32

### 8.5 
What is the effect of allowing two entries in a page table to point to the same page frame in memory? Explain how this effect could be used to decrease the amount of time needed to copy a large amount of memory from one place to another. What effect would updating some byte on the one page have on the other page?

#### Answer:
> Nghe như là kiểu map vào 1 chỗ, nếu thế thì khi copy sẽ chỉ copy 1 lần, thay vì copy 2 lần. 
Còn nếu update thì sẽ xảy ra vụ thay đổi. Ê nghe giống con trỏ hay reference ở cpp nhỉ. 


### 8.6 
Describe a mechanism by which one segment could belong to the address space of two different processes.

#### Answer:



### 8.7 
Sharing segments among processes without requiring that they have the same segment number is possible in a dynamically linked segmentation system. 
    a. Define a system that allows static linking and sharing of segments without requiring that the segment numbers be the same. 
    b. Describe a paging scheme that allows pages to be shared without requiring that the page numbers be the same. 

#### Answer:


### 8.8 
In the IBM/370, memory protection is provided through the use of keys. A key is a 4-bit quantity. Each 2-K block of memory has a key (the storage key) associated with it. The CPU also has a key (the protection key) associated with it. A store operation is allowed only if both keys are equal or if either is 0. Which of the following memory-management schemes could be used successfully with this hardware?

  a. Bare machine

  b. Single-user system

  c. Multiprogramming with a fixed number of processes

  d. Multiprogramming with a variable number of processes

  e. Paging

  f. Segmentation


#### Answer:


### 9.1 
Under what circumstances do page faults occur? Describe the actions taken by the operating system when a page fault occurs. 

#### Answer:

### 9.2 
Assume that you have a page-reference string for a process with m frames (initially all empty). The page-reference string has length p, and n distinct page numbers occur in it. Answer these questions for any page-replacement algorithms:

  a. What is a lower bound on the number of page faults?

  b. What is an upper bound on the number of page faults?

#### Answer:


### 9.3 
Consider the page table shown in Figure 9.30 for a system with 12-bit virtual and physical addresses and with 256-byte pages. The list of free page frames is D, E, F (that is, D is at the head of the list, E is second, and F is last).

Page | Page Frame 
---|---
0 | -
1 | 2
2 | C 
3 | A
4 | -
5 | 4
6 | 3
7 | –
8 | B
9 | 0

Convert the following virtual addresses to their equivalent physical addresses in hexadecimal. All numbers are given in hexadecimal. (A dash for a page frame indicates that the page is not in memory.)

- 9EF
- 111
- 700
- 0FF

#### Answer:


### 9.4 
Consider the following page-replacement algorithms. Rank these algorithms on a five-point scale from “bad” to “perfect” according to their page-fault rate. Separate those algorithms that suffer from Belady’s anomaly from those that do not.

  a. LRU replacement

  b. FIFO replacement

  c. Optimal replacement

  d. Second-chance replacement

#### Answer:


### 9.5 
Discuss the hardware support required to support demand paging.

#### Answer:

### 9.6 
An operating system supports a paged virtual memory. The central processor has a cycle time of 1 microsecond. It costs an additional 1 microsecond to access a page other than the current one. Pages have 1,000 words, and the paging device is a drum that rotates at 3,000 revolutions per minute and transfers 1 million words per second. The following statistical measurements were obtained from the system:
- One percent of all instructions executed accessed a page other than
the current page.
- Of the instructions that accessed another page, 80 percent accessed
a page already in memory.
- When a new page was required, the replaced page was modified 50
percent of the time.

Calculate the effective instruction time on this system, assuming that the system is running one process only and that the processor is idle during drum transfers.

#### Answer:

### 9.7 
Consider the two-dimensional array A: 
`int A[][] = new int[100][100];` 
where `A[0][0]` is at location 200 in a paged memory system with pages of size 200. A small process that manipulates the matrix resides in page 0 (locations 0 to 199). Thus, every instruction fetch will be from page 0. For three page frames, how many page faults are generated by the following array-initialization loops? Use LRU replacement, and assume that page frame 1 contains the process and the other two are initially empty.

  a. 
```
for (int j = 0; j < 100; j++)
for (int i = 0; i < 100; i++)
A[i][j] = 0;
```

  b. 
```
for (int i = 0; i < 100; i++)
for (int j = 0; j < 100; j++)
A[i][j] = 0;
```

#### Answer:

### 9.8 
Consider the following page reference string: 1, 2, 3, 4, 2, 1, 5, 6, 2, 1, 2, 3, 7, 6, 3, 2, 1, 2, 3, 6. How many page faults would occur for the following replacement algorithms, assuming one, two, three, four, five, six, and seven frames? Remember that all frames are initially empty, so your first unique pages will cost one fault each.
- LRU replacement
- FIFO replacement
- Optimal replacement

#### Answer:

### 9.9 
Suppose that you want to use a paging algorithm that requires a reference bit (such as second-chance replacement or working-set model), but the hardware does not provide one. Sketch how you could simulate a reference bit even if one were not provided by the hardware, or explain why it is not possible to do so. If it is possible, calculate what the cost would be. 

#### Answer:

### 9.10 
You have devised a new page-replacement algorithm that you think may be optimal. In some contorted test cases, Belady’s anomaly occurs. Is the new algorithm optimal? Explain your answer.

#### Answer:


### 9.11 
Segmentation is similar to paging but uses variable-sized “pages.” Define two segment-replacement algorithms, one based on the FIFO pagereplacement scheme and the other on the LRU page-replacement scheme. Remember that since segments are not the same size, the segment that is chosen for replacement may be too small to leave enough consecutive locations for the needed segment. Consider strategies for systems where segments cannot be relocated and strategies for systems where they can.

#### Answer:


### 9.12 
Consider a demand-paged computer system where the degree of multiprogramming is currently fixed at four. The system was recently measured to determine utilization of the CPU and the paging disk. Three alternative results are shown below. For each case, what is happening? Can the degree of multiprogramming be increased to increase the CPU utilization? Is the paging helping?

a. CPU utilization 13 percent; disk utilization 97 percent

b. CPU utilization 87 percent; disk utilization 3 percent

c. CPU utilization 13 percent; disk utilization 3 percent

#### Answer:


### 9.13 
We have an operating system for a machine that uses base and limit registers, but we have modified the machine to provide a page table. Can the page tables be set up to simulate base and limit registers? How can they be, or why can they not be?

#### Answer:











